# Generated by Django 4.2 on 2025-05-07 20:50

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_campaign_min_balance_alter_campaign_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victiminfo',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=8, max_length=12, prefix='CL', primary_key=True, serialize=False, unique=True),
        ),
    ]
